### ISSUE TITLE
osquery 5.0 breaking changes

### ISSUE THREAD

**Issue by directionless** [autopkg/weswhet-recipes#1]
Hi! You probably need to update your autopkg in light of the osquery 5.0 breaking changes. 
* macOS packages are now code signed by the osquery foundation
* If you use the default package, it’s now in /opt/osquery
* There’s an app bundle. this was needed to support the endpoint security permissions

See https://github.com/osquery/osquery/releases/tag/5.0.1 for more (edited)

**Comment by weswhet** [comment]
I believe I handled this with commit. f78434f1a46d57b0894c3f4555e1303853adf5df

Appreciate the heads up and all your work on osquery.
